name: cs570s22
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.6
  - pandas=1.3.3
  - plotnine=0.8.0
  - pycairo=1.19.1
  - pytorch=1.9.1
  - scikit-learn=0.24.2
  - pip=21.0.1
  - pip:
    - numpy==1.19.5
    - tensorboard==2.6.0
    - torchmetrics==0.5.1
    - torchvision==0.10.1
