To do the homeworks you need to use python; it is recommended to
install/use [[https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html][anaconda/miniconda]], with either
- one of the [[https://docs.anaconda.com/anaconda/user-guide/tasks/integration/index.html][IDEs described on the anaconda docs]], (for beginners,
  choose one that you have used in the past), or
- [[https://www.emacswiki.org/emacs/PythonProgrammingInEmacs][Elpy/LspMode]] IDE (for students who already know/use emacs, or who
  want to learn, [[http://emacsrocks.com/][here are some very informative "emacs rocks"
  screencasts which show the power of emacs]]).

** Instructions for conda (all students)

After [[https://docs.conda.io/en/latest/miniconda.html][downloading conda]] you can install all packages for this class,
same versions that I use, via:

#+begin_src shell-script
conda env create -f https://raw.githubusercontent.com/tdhock/cs570-spring-2022/master/environment.yml
#+end_src

That should create a new "cs570s22" python environment. Before you
activate an environment, you need to setup your shell for the first
time.

#+begin_src shell-script
conda init bash
#+end_src

That should put some code in your ~/.bash_profile, I had to copy it to
my ~/.bashrc to get it to work on my setup (git bash in emacs shell on
windows). After restarting your shell you should see a (base) prefix
in your prompt, which indicates the name of the currently activated
conda environment.  You can activate another environment via

#+begin_src shell-script
conda activate cs570s22
#+end_src

After activation, that environment will be used for new python
processes, looking for python modules, etc.

** Python support in emacs (only students who want to use emacs)

To get python support in emacs I had to install emacs packages
(elpy,conda). To do that first you need to put the following in your
~/.emacs file to tell it to download packages from the MELPA
repository,

#+BEGIN_SRC elisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
#+END_SRC

Then run M-x package-list-packages (M-x means hold down the option/alt
key and type x) to see a list of packages you can install. Search for
elpy and conda (maybe with C-s, meaning hold down control key and type
s), mark for installation by typing i, then type x to install all
packages marked for installation. Finally to tell emacs to use elpy
with python code, and my conda environments, I put the following in my
~/.emacs file:

#+begin_src elisp
(elpy-enable)
(setq
 conda-anaconda-home (expand-file-name "~/miniconda3")
 conda-env-home-directory (expand-file-name "~/miniconda3"))
#+end_src

In emacs When editing a python file we can "activate" the conda
environment via M-x conda-env-activate RET cs570s22 RET then C-c C-z
to get an interactive shell, then
- C-RET to send line and step,
- C-c to send highlighted region.

See
https://elpy.readthedocs.io/en/latest/ide.html for more elpy key
commands (sending code from python code files to the interactive
shell), and https://realpython.com/emacs-the-best-python-editor/ for a
nice tutorial about emacs and python.
